name: zione
description: Delforte operation agenda app for appointments and tickets.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  equatable: ^2.0.3
  url_launcher: ^6.0.18
  font_awesome_flutter: ^10.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  modal_bottom_sheet: ^2.0.0
  date_time_picker: ^2.1.0
  logging: ^1.0.2
  dartz: ^0.10.1
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  flutter_modular: ^4.5.0
  triple: ^1.5.0+1
  flutter_triple: ^1.2.7+2
  table_calendar: ^3.0.5
  timelines: ^0.1.0
  flex_color_scheme: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  hive_test: ^1.0.1
  mobx_codegen: ^2.0.5+2
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

platforms:
  linux:
  android:
  ios:

flutter:
  uses-material-design: true
  assets:
    - test/modules/agenda/stubs/agenda_endpoint_json_response.json
